name = "soutu-bot"
main = "src/index.js"
compatibility_date = "2024-05-01"

[[kv_namespaces]]
binding = "KV"
id = "${KV_ID}"

[[d1_databases]]
binding = "DB"
database_name = "soutu-db"
database_id = "${D1_ID}"

[vars]
TZ = "Asia/Shanghai"
