name = "soutu-bot"
main = "src/index.js"
compatibility_date = "2026-01-10"
workers_dev = true

[[d1_databases]]
binding = "DB"
database_name = "soutu-bot"
database_id = "bca36663-b43f-426c-972e-fcece7125987"

[[kv_namespaces]]
binding = "KV"
id = "b55a275566a34c3f81a2903e14af4a19"

[triggers]
crons = ["*/5 * * * *"]

[vars]
# Non-sensitive configuration only. Store BOT_TOKEN as a secret.
ADMIN_USER_IDS = "7204268059"
TZ = "Asia/Shanghai"

# You will set secrets via: wrangler secret put BOT_TOKEN
