name = "soutu-worker"
main = "src/index.js"
compatibility_date = "2024-05-01"

[[kv_namespaces]]
binding = "KV"
id = "YOUR_KV_ID"

[[d1_databases]]
binding = "DB"
database_name = "soutu-db"
database_id = "YOUR_D1_ID"

[vars]
TZ = "Asia/Shanghai"
